name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install dependencies
      run: |
        uv sync --group test
    - name: Run tests
      run: |
        python -m pytest
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: pypi
      url: https://pypi.org/p/llm-yt-transcript/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.13
        enable-cache: true
    - name: Install dependencies
      run: |
        uv add setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
